### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by torquil** [sgorpi/midex8#1]
When building on Debian Testing (of today) against linux 5.4 I get the following warning at the end of the build process:

`#1: FILE: /home/torquil/src/midex8/src/kernel/sound/usb/midex/midex.c:1:
+/*

total: 0 errors, 1 warnings, 1693 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

/home/torquil/src/midex8/src/kernel/sound/usb/midex/midex.c has style problems, please review.`

Best regards,
Torquil Sørensen

**Comment by sgorpi** [comment]
Hi, thanks for the feedback, didn't know there were people interested.

The warning is one of the 'checkpatch.pl script that checks code style. It shouldn't be a reason for the build to fail. I've just pushed a new update that, among others, hides this check behind a switch (-c), because it may confuse the user (you)... Hope that helps!

Let me know if you run into anything else!
Sgorpi
